### ISSUE TITLE
Setup of ITaxProviderSetting #2 uses from description constant

### ISSUE THREAD

**Issue by ddunngh** [Acumatica/DummyTaxProvider#1]
new TaxProviderSetting(TaxProviderID, WriteTraceSettingID,  2, Messages.ActiveSettingDisplaytName,(true).ToString(), TaxProviderSettingControlType.Checkbox)

should be using Messages.WriteTraceDisplaytName instead of Messages.ActiveSettingDisplaytName

**Comment by Dmitrii-Naumov** [comment]
Thanks! Done!
